name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers the workflow when you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # This publishes everything in your repo
          publish_branch: gh-pages  # Specify the branch for GitHub Pages
