name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu  # Use 'ubuntu' for Ubuntu AMIs
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "."
          target: "/var/www/html/"  # Where your web files will be hosted
